<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style>
  label { display: block; }
  </style>
</head>
<body>
  <form method="post">
    <div class="form__field">
      <label>Name</label>
      <input name="name">
    </div>

    <div class="form__field">
      <label>E-Mail</label>
      <input name="email">
    </div>

    <div class="form__field">
      <label>Subject</label>
      <input name="subject" value="Lorem Ipsum">
    </div>

    <div class="form__field">
      <label>Message</label>
      <textarea cols="80" name="message">
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse eos quidem, odit adipisci animi ducimus corrupti, architecto impedit voluptatum ipsum non deleniti, maiores qui voluptatibus nemo. Consectetur id magni dolor!
      </textarea>
    </div>

    <button type="submit"> Submit </button>
  </form>
</body>
</html>